-- AlterTable
ALTER TABLE `ACUDIENTE` MODIFY `NUMERO_CONTACTO_ACU` BIGINT NOT NULL;

-- AlterTable
ALTER TABLE `PERSONA` MODIFY `NUMERO_DOC_PER` BIGINT NOT NULL,
    MODIFY `NUMERO_CONTACTO_PER` BIGINT NULL;
