-- AlterTable
ALTER TABLE `ACUDIENTE` MODIFY `NUMERO_CONTACTO_ACU` VARCHAR(191) NOT NULL;

-- AlterTable
ALTER TABLE `PERSONA` MODIFY `NUMERO_DOC_PER` VARCHAR(191) NOT NULL,
    MODIFY `NUMERO_CONTACTO_PER` VARCHAR(191) NULL;
