/*
  Warnings:

  - You are about to drop the column `ID_ESTUDIANTE` on the `NOTA` table. All the data in the column will be lost.
  - You are about to drop the column `VALOR_NOTA` on the `NOTA` table. All the data in the column will be lost.

*/
-- DropForeignKey
ALTER TABLE `NOTA` DROP FOREIGN KEY `NOTA_ID_ESTUDIANTE_fkey`;

-- AlterTable
ALTER TABLE `NOTA` DROP COLUMN `ID_ESTUDIANTE`,
    DROP COLUMN `VALOR_NOTA`;

-- CreateTable
CREATE TABLE `NOTAS_ESTUDIANTE` (
    `VALOR_NOTA` DOUBLE NOT NULL,
    `ID_NOTA` INTEGER NOT NULL,
    `ID_ESTUDIANTE` INTEGER NOT NULL,

    PRIMARY KEY (`ID_NOTA`, `ID_ESTUDIANTE`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `NOTAS_ESTUDIANTE` ADD CONSTRAINT `NOTAS_ESTUDIANTE_ID_NOTA_fkey` FOREIGN KEY (`ID_NOTA`) REFERENCES `NOTA`(`ID_NOTA`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `NOTAS_ESTUDIANTE` ADD CONSTRAINT `NOTAS_ESTUDIANTE_ID_ESTUDIANTE_fkey` FOREIGN KEY (`ID_ESTUDIANTE`) REFERENCES `ESTUDIANTE`(`ID_PERSONA`) ON DELETE RESTRICT ON UPDATE CASCADE;
